import { Rubik } from "next/font/google";
import "./globals.css";
import { Providers } from "./Providers";
const rubik = Rubik({ subsets: ["latin"] });

export const metadata = {
  title: "Web dev",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <Providers>{children}</Providers>
        <div className="area">
          <ul className="circles">
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
          </ul>
        </div>
      </body>
    </html>
  );
}
